# Generated by Django 5.0.6 on 2024-06-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=23)),
                ('city', models.CharField(max_length=23)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('pc', models.ImageField(upload_to='profiles/')),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'other')], max_length=23)),
            ],
        ),
    ]
